# Generated by Django 5.1.7 on 2025-04-03 20:02

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('company_email', models.EmailField(max_length=60, unique=True)),
                ('company_name', models.CharField(max_length=95, unique=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('employees', models.IntegerField(blank=True, default=None, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('company_logo', models.ImageField(blank=True, default=accounts.models.get_default_image, null=True, upload_to=accounts.models.get_image_filepath)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
