# Generated by Django 5.2 on 2025-05-04 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('can_read_contact', models.BooleanField(default=False)),
                ('can_edit_contact', models.BooleanField(default=False)),
                ('can_delete_contact', models.BooleanField(default=False)),
                ('can_permanent_delete_contact', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AccessPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_shared', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_with', to='accounts.businessuser')),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.businessuser')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.role')),
            ],
            options={
                'unique_together': {('owner', 'shared_with')},
            },
        ),
    ]
