# Generated by Django 5.2 on 2025-05-04 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_role_accesspermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.businessuser'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('user', 'name')},
        ),
    ]
