# Generated by Django 5.2 on 2025-05-04 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_role_user_alter_role_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesspermission',
            name='shared_with',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessible_accounts', to='accounts.businessuser'),
        ),
    ]
