# Generated by Django 5.2 on 2025-05-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_accesspermission_shared_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessuser',
            name='public_id',
            field=models.UUIDField(blank=True, default=None, null=True, unique=True),
        ),
    ]
