# Generated by Django 5.2 on 2025-05-04 08:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_businessuser_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessuser',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
