# Generated by Django 5.2 on 2025-05-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_businessuser_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_add_contact',
            field=models.BooleanField(default=False),
        ),
    ]
