# Generated by Django 5.2 on 2025-05-04 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_role_can_add_documents_role_can_add_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='can_add_project',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_delete_project',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_edit_project',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_permanent_delete_project',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_read_project',
        ),
    ]
