# Generated by Django 5.2 on 2025-05-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_role_can_add_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_add_project',
            field=models.BooleanField(default=False),
        ),
    ]
