# Generated by Django 5.2 on 2025-05-04 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_role_can_add_project_and_more'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAccessPermisssion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_read_project', models.BooleanField(default=False)),
                ('can_add_project', models.BooleanField(default=False)),
                ('can_edit_project', models.BooleanField(default=False)),
                ('can_delete_project', models.BooleanField(default=False)),
                ('can_permanent_delete_project', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_project_permissions', to='client.project')),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_permissions', to='accounts.businessuser')),
            ],
            options={
                'unique_together': {('project', 'shared_with')},
            },
        ),
    ]
