# Generated by Django 5.2 on 2025-05-04 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_role_can_add_project_and_more'),
        ('client', '0002_projectaccesspermisssion'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectaccesspermisssion',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_shared_with', to='accounts.businessuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectaccesspermisssion',
            name='shared_with',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_accessible_accounts', to='accounts.businessuser'),
        ),
    ]
