# Generated by Django 5.2 on 2025-05-04 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_projectaccesspermisssion_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectaccesspermisssion',
            name='can_add_project',
        ),
    ]
