# Generated by Django 5.2 on 2025-05-06 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_role_can_add_project'),
        ('client', '0004_remove_projectaccesspermisssion_can_add_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAccessPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_read_project', models.BooleanField(default=False)),
                ('can_edit_project', models.BooleanField(default=False)),
                ('can_delete_project', models.BooleanField(default=False)),
                ('can_permanent_delete_project', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_project_permissions', to='client.project')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.role')),
            ],
        ),
        migrations.DeleteModel(
            name='ProjectAccessPermisssion',
        ),
    ]
