# Generated by Django 5.2 on 2025-05-08 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_role_can_add_project'),
        ('client', '0005_projectaccesspermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('In-Progress', 'In-Progress'), ('Completed', 'Completed')], default='New', max_length=20)),
                ('priority', models.CharField(choices=[('Normal', 'Normal'), ('Urgent', 'Urgent'), ('Low', 'Low')], default='Normal', max_length=20)),
                ('type', models.CharField(choices=[('Call', 'Call'), ('WhatsApp', 'WhatsApp'), ('Gmail', 'Gmail'), ('Other', 'Other')], max_length=20)),
                ('due_date', models.DateField()),
                ('due_time', models.TimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_tasks', to='accounts.businessuser')),
                ('related_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='accounts.businessuser')),
            ],
        ),
    ]
