# Generated by Django 5.1.7 on 2025-05-02 08:30

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='last_edit',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='country_code',
            field=models.CharField(blank=True, choices=[('+1', 'United States (+1)'), ('+44', 'United Kingdom (+44)'), ('+91', 'India (+91)'), ('+81', 'Japan (+81)'), ('+61', 'Australia (+61)'), ('+49', 'Germany (+49)'), ('+971', 'UAE (+971)'), ('+86', 'China (+86)'), ('+33', 'France (+33)')], default='+91', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number without country code.', regex='^\\d{5,12}$')]),
        ),
    ]
